# Angel API URLs
# Base URL
angel.base.url=https://apiconnect.angelone.in

# Auth
angel.login=/rest/auth/angelbroking/user/v1/loginByPassword
angel.generate.token=/rest/auth/angelbroking/jwt/v1/generateTokens
angel.get.profile=/rest/secure/angelbroking/user/v1/getProfile

# Market
angel.ltp=/rest/secure/angelbroking/order/v1/getLtpData
angel.search.scrip=/rest/secure/angelbroking/order/v1/searchScrip

# Order
angel.place.order=/rest/secure/angelbroking/order/v1/placeOrder
angel.modify.order=/rest/secure/angelbroking/order/v1/modifyOrder
angel.cancel.order=/rest/secure/angelbroking/order/v1/cancelOrder
angel.order.book=/rest/secure/angelbroking/order/v1/getOrderBook
angel.trade.book=/rest/secure/angelbroking/order/v1/getTradeBook
angel.position=/rest/secure/angelbroking/order/v1/getPosition

# WebSocket
angel.ws.url=wss://smartapisocket.angelone.in/smart-stream

# Contract Master
angel.contract.master=https://margincalculator.angelbroking.com/OpenAPI_File/files/OpenAPIScripMaster.json
