[nse]
nse.base.url=https://www.nseindia.com
nse.option.chain.url=https://www.nseindia.com/api/option-chain-indices?symbol=NIFTY

[settings]
option.poll.interval=15

[ingestion]
data.source=url
csv.file.path=data/option_chain.csv
excel.file.path=data/option_chain.xlsx

[request]
request.user.agent=Mozilla/5.0
